name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - master
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
    timeout-minutes: 30
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CONDITION }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_RUNS_ON }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_RUN_SCRIPT }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_KEY }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_TEST_LINUX_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CONDITION }}
      NUKE_PRE_SETUP_TEST_LINUX_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_RUNS_ON }}
      NUKE_PRE_SETUP_TEST_LINUX_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_RUN_SCRIPT }}
      NUKE_PRE_SETUP_TEST_LINUX_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_KEY }}
      NUKE_PRE_SETUP_TEST_LINUX_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_TEST_LINUX_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CONDITION }}
      NUKE_PRE_SETUP_TEST_WINDOWS_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_RUNS_ON }}
      NUKE_PRE_SETUP_TEST_WINDOWS_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_RUN_SCRIPT }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_KEY }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_SUBMODULES }}
  MULTIFORMATDATACONVERTERBUILD:
    name: Build - multi-format-data-converter (MultiFormatDataConverterBuild)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke MultiFormatDataConverterBuild
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_RUN_SCRIPT }} Run --args "MultiFormatDataConverterBuild"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build___multi-format-data-converter___MULTIFORMATDATACONVERTERBUILD
        path: ./.nuke/temp/artifacts-upload/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERBUILD_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  TEST_LINUX:
    name: Test - multi-format-data-converter (TEST_LINUX)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke TEST_LINUX
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_RUN_SCRIPT }} Run --args "TEST_LINUX"
    needs:
    - PRE_SETUP
    - MULTIFORMATDATACONVERTERBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_LINUX_CONDITION == 'true' && needs.MULTIFORMATDATACONVERTERBUILD.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  TEST_WINDOWS:
    name: Test - multi-format-data-converter (TEST_WINDOWS)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke TEST_WINDOWS
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_RUN_SCRIPT }} Run --args "TEST_WINDOWS"
    needs:
    - PRE_SETUP
    - MULTIFORMATDATACONVERTERBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_TEST_WINDOWS_CONDITION == 'true' && needs.MULTIFORMATDATACONVERTERBUILD.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  MULTIFORMATDATACONVERTERPUBLISH:
    name: Publish - multi-format-data-converter (MultiFormatDataConverterPublish)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: build___multi-format-data-converter___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke MultiFormatDataConverterPublish
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_RUN_SCRIPT }} Run --args "MultiFormatDataConverterPublish"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish___multi-format-data-converter___MULTIFORMATDATACONVERTERPUBLISH
        path: ./.nuke/temp/artifacts-upload/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - MULTIFORMATDATACONVERTERBUILD
    - TEST_LINUX
    - TEST_WINDOWS
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_MULTIFORMATDATACONVERTERPUBLISH_CONDITION == 'true' && needs.MULTIFORMATDATACONVERTERBUILD.result == 'success' && needs.TEST_LINUX.result == 'success' && needs.TEST_WINDOWS.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: publish___*
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
    needs:
    - PRE_SETUP
    - MULTIFORMATDATACONVERTERBUILD
    - TEST_LINUX
    - TEST_WINDOWS
    - MULTIFORMATDATACONVERTERPUBLISH
    if: success() || failure() || always()
    timeout-minutes: 30
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_MULTIFORMATDATACONVERTERBUILD: ${{ needs.MULTIFORMATDATACONVERTERBUILD.result }}
      NUKE_RUN_RESULT_GITHUB_TEST_LINUX: ${{ needs.TEST_LINUX.result }}
      NUKE_RUN_RESULT_GITHUB_TEST_WINDOWS: ${{ needs.TEST_WINDOWS.result }}
      NUKE_RUN_RESULT_GITHUB_MULTIFORMATDATACONVERTERPUBLISH: ${{ needs.MULTIFORMATDATACONVERTERPUBLISH.result }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
